#!/usr/bin/env python3
"""Facts this fork states in more than one place, checked mechanically.

Every check here exists because the same fact lives in several files, and a
merge that git reports as clean can still leave them disagreeing. Two of these
have already happened:

  * The protocol number was bumped 6 -> 7 on two branches independently. Both
    edited the same lines, so git *did* conflict - but the resolution is a trap:
    both sides say 7, so picking either looks correct and ships two features
    sharing one version. checkProtocol catches that after the fact.
  * D3DMATERIAL9 channels were claimed by a feature without being added to the
    field map, so the map still advertised them as free.

Run with no arguments from anywhere in the repo. Exit code 0 = consistent.
CI runs this on every push, with no path filter, because doc-only changes are
exactly when these drift.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

failures: list[str] = []
warnings: list[str] = []
checks_run = 0


def fail(check: str, message: str) -> None:
    failures.append(f"[{check}] {message}")


def warn(check: str, message: str) -> None:
    """For drift that cannot be fixed from here.

    A check that blocks a merge on something the author physically cannot do -
    RtxOptions.md is generated by running the runtime on Windows - gets disabled
    the first time it is inconvenient, and then catches nothing at all. These
    are printed on every run instead.
    """
    warnings.append(f"[{check}] {message}")


def read(rel: str) -> str | None:
    p = REPO / rel
    return p.read_text(encoding="utf-8", errors="replace") if p.is_file() else None


def tracked_files() -> list[str]:
    out = subprocess.run(
        ["git", "-C", str(REPO), "ls-files"], capture_output=True, text=True, check=False
    )
    return out.stdout.splitlines() if out.returncode == 0 else []


# ---------------------------------------------------------------------------


def check_conflict_markers() -> None:
    """A committed conflict marker means a resolution was never finished."""
    global checks_run
    checks_run += 1
    # Written split so this file does not match its own check.
    starts = "<" * 7
    ends = ">" * 7
    suffixes = {".md", ".h", ".hpp", ".cpp", ".c", ".py", ".build", ".yml", ".slang", ".slangh"}
    for rel in tracked_files():
        if Path(rel).suffix not in suffixes:
            continue
        if rel == "scripts/check_dusklight_invariants.py":
            continue
        text = read(rel)
        if text is None:
            continue
        for n, line in enumerate(text.splitlines(), 1):
            if line.startswith(starts) or line.startswith(ends):
                fail("conflict-markers", f"{rel}:{n} leftover merge marker")


def check_protocol() -> None:
    """kRequiredProtocol, the prose, and the version registry must agree.

    The registry line is what makes two features that both bump the protocol
    visible: each adds an 'N = what it added' entry, so duplicate numbers or a
    max that disagrees with the code is a bad merge resolution, not a typo.
    """
    global checks_run
    checks_run += 1

    src = read("src/dxvk/imgui/dxvk_imgui.cpp")
    doc = read("documentation/DusklightOverlay.md")
    if src is None or doc is None:
        fail("protocol", "expected source or documentation file is missing")
        return

    m = re.search(r"kRequiredProtocol\s*=\s*(\d+)", src)
    if not m:
        fail("protocol", "could not find 'kRequiredProtocol = N' in dxvk_imgui.cpp")
        return
    code_value = int(m.group(1))

    # "**Protocol is at 7** (3 = overlay + warp, 4 = the clock, ...)"
    reg = re.search(r"\*\*Protocol is at (\d+)\*\*\s*\(([^)]*)\)", doc)
    if not reg:
        fail(
            "protocol",
            "DusklightOverlay.md has no '**Protocol is at N** (N = what it added, ...)' "
            "registry line; it is what makes a double bump visible",
        )
        return

    if int(reg.group(1)) != code_value:
        fail(
            "protocol",
            f"DusklightOverlay.md says protocol {reg.group(1)}, "
            f"kRequiredProtocol says {code_value}",
        )

    entries = re.findall(r"(\d+)\s*=\s*([^,)]+)", reg.group(2))
    seen: dict[int, str] = {}
    for num_s, what in entries:
        num = int(num_s)
        if num in seen:
            fail(
                "protocol",
                f"protocol {num} is claimed twice in the registry: "
                f"'{seen[num].strip()}' and '{what.strip()}'. Two features bumped to the same "
                f"version - one of them needs the next number, and kRequiredProtocol with it",
            )
        seen[num] = what
    if seen and max(seen) != code_value:
        fail(
            "protocol",
            f"registry's highest entry is {max(seen)} but kRequiredProtocol is {code_value}; "
            f"a bump added the constant without recording what it was for",
        )

    # The prose statement earlier in the same document.
    for n, line in enumerate(doc.splitlines(), 1):
        cur = re.search(r"\*\*Currently (\d+)\.\*\*", line)
        if cur and int(cur.group(1)) != code_value:
            fail(
                "protocol",
                f"DusklightOverlay.md:{n} says 'Currently {cur.group(1)}' "
                f"but kRequiredProtocol is {code_value}",
            )

    claude = read("CLAUDE.md")
    if claude:
        for n, line in enumerate(claude.splitlines(), 1):
            c = re.search(r"\*\*Protocol is at (\d+)\.?\*\*", line)
            if c and int(c.group(1)) != code_value:
                fail(
                    "protocol",
                    f"CLAUDE.md:{n} says protocol {c.group(1)} but the code says {code_value}",
                )


def check_side_channel_map() -> None:
    """Every D3DMATERIAL9 channel the fork reads must be in the field map.

    The map is the only place that says which channels are still spare, so a
    channel taken without a row invites the next feature to take it again.
    Prose home is aurora's remix-material-interface.md §2; the machine-readable
    copy is here, in the repo that does the reading.
    """
    global checks_run
    checks_run += 1

    registry = read("documentation/DusklightSideChannels.md")
    if registry is None:
        fail("side-channels", "documentation/DusklightSideChannels.md is missing")
        return

    # Only the allocation table counts, not prose. Rows look like
    #   | `Ambient.g` | what it carries | where | since |
    # Scanning the whole document instead would let a sentence that merely
    # mentions a channel stand in for its row - which it did, until a test
    # deleted a row and this check stayed silent.
    documented: set[tuple[str, str]] = set()
    for line in registry.splitlines():
        if not line.lstrip().startswith("|"):
            continue
        first_cell = line.split("|")[1] if line.count("|") >= 2 else ""
        for field, chans in re.findall(
            r"`(Ambient|Diffuse|Specular|Emissive)\.([rgba]+)`", first_cell
        ):
            for c in chans:
                documented.add((field, c))

    if "`Power`" in registry:
        documented.add(("Power", ""))

    # rtx_materials.cpp is exhaustive on purpose - computeIdentityHash reads every
    # channel including the spare ones, so that a future claim is covered by the
    # hash the moment it is written. Scanning it here would report every spare
    # channel as an undocumented read. It gets the opposite check instead, below.
    HASH_SITE = "src/dxvk/rtx_render/rtx_materials.cpp"

    read_channels: dict[tuple[str, str], str] = {}
    pattern = re.compile(
        r"(?:getLegacyMaterial\(\)|d3dMaterial|legacy|material|mat)\s*\.\s*"
        r"(?:(Ambient|Diffuse|Specular|Emissive)\s*\.\s*([rgba])|(Power))\b"
    )
    for rel in tracked_files():
        if not rel.startswith("src/") or Path(rel).suffix not in {".h", ".hpp", ".cpp"}:
            continue
        if rel == HASH_SITE:
            continue
        text = read(rel)
        if text is None:
            continue
        for n, line in enumerate(text.splitlines(), 1):
            stripped = line.lstrip()
            if stripped.startswith("//") or stripped.startswith("*"):
                continue
            for field, chan, power in pattern.findall(line):
                key = ("Power", "") if power else (field, chan)
                read_channels.setdefault(key, f"{rel}:{n}")
            # A reference bound to the whole D3DCOLORVALUE reads every channel of
            # it: `const D3DCOLORVALUE& e = mat.getLegacyMaterial().Emissive;` and
            # then `e.r`. Without this the reverse direction reports Emissive.rgb
            # and Diffuse.rgb as unread, which they are not.
            for field in re.findall(
                r"(?:getLegacyMaterial\(\)|d3dMaterial)\s*\.\s*"
                r"(Ambient|Diffuse|Specular|Emissive)\b(?!\s*\.)",
                line,
            ):
                for c in "rgba":
                    read_channels.setdefault((field, c), f"{rel}:{n}")

    def channel_name(key: tuple[str, str]) -> str:
        return f"{key[0]}.{key[1]}" if key[1] else key[0]

    for key, where in sorted(read_channels.items()):
        if key not in documented:
            fail(
                "side-channels",
                f"{where} reads D3DMATERIAL9::{channel_name(key)} but it has no row in "
                f"documentation/DusklightSideChannels.md - add one, or the map will keep "
                f"advertising that channel as spare",
            )

    # The reverse direction. A row with nothing reading it is what a merge produces
    # when a branch that forked before a channel existed wins the conflict: the code
    # that claimed the channel is gone and the table still describes it. Checking
    # only reads-imply-rows passes that tree green, which is how HD texture packs
    # nearly went missing on 2026-08-11.
    for key in sorted(documented - set(read_channels)):
        # Emissive.a is documented as "reported, not used" - nothing reads it by
        # design, and that is stated in its row rather than being an omission.
        row = next(
            (l for l in registry.splitlines()
             if l.lstrip().startswith("|") and f"`{channel_name(key)}`" in l.split("|")[1]),
            "",
        )
        if "not used" in row or "reported, not used" in row:
            continue
        fail(
            "side-channels",
            f"documentation/DusklightSideChannels.md has a row for D3DMATERIAL9::"
            f"{channel_name(key)} but nothing in src/ reads it - either a merge dropped the "
            f"feature that claimed it, or the row is stale",
        )


def check_side_channels_hashed() -> None:
    """Every allocated side channel must be in LegacyMaterialData::computeIdentityHash.

    Two draws differing only in a side channel otherwise produce the same identity
    hash, and SceneManager's preserve path goes on handing an instance the material
    it built from the other one - a stale material, with nothing logged anywhere.

    Power was left out of that hash on the stated grounds that nothing read it, and
    the water feature then read it, on a branch that never touched rtx_materials.cpp.
    The comment saying Power was unread stayed true-looking for a week. This makes
    the claim and the hash one thing rather than two.
    """
    global checks_run
    checks_run += 1

    src = read("src/dxvk/rtx_render/rtx_materials.cpp")
    registry = read("documentation/DusklightSideChannels.md")
    if src is None or registry is None:
        fail("hash-coverage", "rtx_materials.cpp or DusklightSideChannels.md is missing")
        return

    hashed: set[tuple[str, str]] = set()
    for field, chan in re.findall(
        r"d3dMaterial\.(Ambient|Diffuse|Specular|Emissive)\.([rgba])\b", src
    ):
        hashed.add((field, chan))
    if re.search(r"d3dMaterial\.Power\b", src):
        hashed.add(("Power", ""))

    for line in registry.splitlines():
        if not line.lstrip().startswith("|"):
            continue
        first_cell = line.split("|")[1] if line.count("|") >= 2 else ""
        keys: list[tuple[str, str]] = []
        for field, chans in re.findall(
            r"`(Ambient|Diffuse|Specular|Emissive)\.([rgba]+)`", first_cell
        ):
            keys.extend((field, c) for c in chans)
        if "`Power`" in first_cell:
            keys.append(("Power", ""))

        for key in keys:
            if key in hashed:
                continue
            name = f"{key[0]}.{key[1]}" if key[1] else key[0]
            fail(
                "hash-coverage",
                f"D3DMATERIAL9::{name} is allocated in DusklightSideChannels.md but "
                f"computeIdentityHash (rtx_materials.cpp) does not read it - two draws "
                f"differing only in that channel will collide and the preserve path will "
                f"serve a stale material",
            )


def check_water_packing_contract() -> None:
    """The water packing is one contract written in two repositories.

    Aurora's GX_AURORA_DUSKLIGHT_WATER_PACK encodes role/tag/layer into
    D3DMATERIAL9::Power; rtx_dusklight_water.h here decodes it. Nothing links the
    two, and if they drift the failure is silent - every draw decodes role=none and
    water renders exactly as it did before the feature existed, which reads as "the
    feature does not work" rather than "the wire changed".

    Aurora's own check_invariants.py checks its half against the sentence in
    remix-material-interface.md §2. This checks that this fork's scale constants
    produce the same sentence, so both halves are pinned to one written formula.
    """
    global checks_run
    checks_run += 1

    src = read("src/dxvk/rtx_render/rtx_dusklight_water.h")
    if src is None:
        return  # water is simply not present on this branch

    tag = re.search(r"kWaterTagScale\s*=\s*(\d+)", src)
    layer = re.search(r"kWaterLayerScale\s*=\s*(\d+)", src)
    if not tag or not layer:
        fail(
            "water-packing",
            "rtx_dusklight_water.h no longer defines kWaterTagScale / kWaterLayerScale - "
            "the decode has no stated relationship to aurora's encode",
        )
        return

    formula = f"tag * {tag.group(1)} + layer * {layer.group(1)} + role"
    for rel in ("documentation/DusklightSideChannels.md",):
        doc = read(rel)
        if doc is None or formula in doc:
            continue
        fail(
            "water-packing",
            f"rtx_dusklight_water.h decodes water as `{formula}` but {rel} does not state "
            f"that formula - aurora encodes from the documented one",
        )


def check_rtx_options_doc() -> None:
    """RtxOptions.md is generated; every rtx.dusklight.* option should be in it."""
    global checks_run
    checks_run += 1

    doc = read("RtxOptions.md")
    if doc is None:
        warn("rtxoptions", "RtxOptions.md is missing")
        return

    declared: dict[str, str] = {}
    decl = re.compile(r'RTX_OPTION[A-Z_]*\(\s*"(rtx\.dusklight[^"]*)"\s*,\s*[^,]+,\s*(\w+)')
    for rel in tracked_files():
        if not rel.startswith("src/") or Path(rel).suffix not in {".h", ".hpp", ".cpp"}:
            continue
        text = read(rel)
        if text is None:
            continue
        for category, name in decl.findall(text):
            declared[f"{category}.{name}"] = rel

    missing = [o for o in sorted(declared) if o not in doc]
    if missing:
        shown = ", ".join(missing[:8]) + (f" (+{len(missing) - 8} more)" if len(missing) > 8 else "")
        warn(
            "rtxoptions",
            f"{len(missing)} rtx.dusklight.* option(s) are declared but absent from "
            f"RtxOptions.md: {shown}. It is generated, never hand-edited - regenerate with "
            f"DXVK_DOCUMENTATION_WRITE_RTX_OPTIONS_MD=1",
        )


def main() -> int:
    check_conflict_markers()
    check_protocol()
    check_side_channel_map()
    check_side_channels_hashed()
    check_water_packing_contract()
    check_rtx_options_doc()

    for w in warnings:
        print(f"WARNING {w}")
    if warnings:
        print(
            "  ^ drift that cannot be fixed from a Linux checkout. Not blocking; "
            "clear it at the next Windows checkpoint.\n"
        )

    if failures:
        print(f"{len(failures)} inconsistency/ies across {checks_run} checks:\n")
        for f in failures:
            print(f"  {f}")
        print(
            "\nThese are facts stated in more than one place that no longer agree. "
            "A clean git merge does not mean they do - see CLAUDE.md, "
            "'Merges that succeed and are still wrong'."
        )
        return 1

    print(f"dusklight invariants: {checks_run} checks passed, {len(warnings)} warning(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
